### ISSUE TITLE
希望能增加对gbk部分未转译的处理

### ISSUE THREAD

**Issue by fqxufo** [cnwhy/GBK.js#2]
比如繁体中文里的"華"，有的gbk编码的网页是处理成了"%C8A"，没有处理成"%C8%41",直接使用您库里的GBK.URI.decodeURI进行转换会报错

**Comment by cnwhy** [comment]
`GBK.URI.decodeURI('%C8')` 报错确实是bug
但没弄清楚你的诉求:
1. `華` > `%C8%41` 这个应该没问题
2. 你说的 `%C8%41` > `%C8A` 应该是别的系统使的不是GBK方式处理,不识别 `%C8%41` 的组合,只认识 `%41`, 所以转成 `A`

**Comment by fqxufo** [comment]
'%C8A'浏览器是可以正常处理成正确的“華”的
我是想希望您可以对这种情况进行处理，将C8和A分开，变成可以正确转换的%C8%41的形式

**Comment by cnwhy** [comment]
虽然没搞清楚你的使用场景;  
但在Chrome下测试的时候发现一个现象:
> 在一个 `GBK` 编码的页面, 使用"A标签" 或 `open()方法` 打开URL `https://www.baidu.com?a=華` 实际跳转的地址会是 `https://www.baidu.com/?a=%C8A`

所以, 我感觉 `GBK.URI.decodeURI` 兼容 `%C8A` 这种情况还是很有必要的.

**Comment by cnwhy** [comment]
看起来你的问题解决了, 我关了
