### ISSUE TITLE
请问gbk.j s和gbk2.js的区别是什么

### ISSUE THREAD

**Issue by MajorAdam** [cnwhy/GBK.js#3]

**Comment by cnwhy** [comment]
只是内部查询编码的实现不一样. 可能有些环境 `gbk2.js` 的速度会稍微快一点.

- `gbk.js` 把码表处理成一个对像里, 检索对像属性的方式, 查询编码;
 - `gbk2.js` 把码表处理成一个有序数组, 用2分法检索, 所以名字里有个2;

**Comment by MajorAdam** [comment]
谢谢
